In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("./sonar_dataset.csv", header=None)
df.sample(5)

0       1       2       3       4       5       6       7       8   \
173  0.0329  0.0216  0.0386  0.0627  0.1158  0.1482  0.2054  0.1605  0.2532   
68   0.0195  0.0142  0.0181  0.0406  0.0391  0.0249  0.0892  0.0973  0.0840   
127  0.0209  0.0261  0.0120  0.0768  0.1064  0.1680  0.3016  0.3460  0.3314   
201  0.0335  0.0258  0.0398  0.0570  0.0529  0.1091  0.1709  0.1684  0.1865   
18   0.0270  0.0092  0.0145  0.0278  0.0412  0.0757  0.1026  0.1138  0.0794   

         9   ...      51      52      53      54      55      56      57  \
173  0.2672  ...  0.0095  0.0151  0.0059  0.0015  0.0053  0.0016  0.0042   
68   0.1191  ...  0.0028  0.0067  0.0120  0.0012  0.0022  0.0058  0.0042   
127  0.4125  ...  0.0057  0.0159  0.0085  0.0372  0.0101  0.0127  0.0288   
201  0.2660  ...  0.0120  0.0039  0.0053  0.0062  0.0046  0.0045  0.0022   
18   0.1520  ...  0.0084  0.0010  0.0018  0.0068  0.0039  0.0120  0.0132   

         58      59  60  
173  0.0053  0.0074   M  
68   0.0067  0.0012   R  
127  0.0129  0.0023   M  
201  0.0005  0.0031   M  
18   0.0070  0.0088   R  

[5 rows x 61 columns]

In [3]:
df.shape


(208, 61)

In [4]:

df.isna().sum()

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

In [5]:
df.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
           dtype='int64')

In [8]:
df[60].value_counts()

M    111
R     97
Name: 60, dtype: int64

In [9]:
X = df.drop(60, axis=1)
y = df[60]
y.head()

0    R
1    R
2    R
3    R
4    R
Name: 60, dtype: object

In [11]:
y = pd.get_dummies(y, drop_first=True)
y  # R --> 1 and M --> 0

R
0    1
1    1
2    1
3    1
4    1
..  ..
203  0
204  0
205  0
206  0
207  0

[208 rows x 1 columns]

In [12]:
y.value_counts()

R
0    111
1     97
dtype: int64

In [13]:
X.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      50      51      52      53      54      55      56  \
0  0.2111  ...  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180   
1  0.2872  ...  0.0125  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140   
2  0.6194  ...  0.0033  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316   
3  0.1264  ...  0.0241  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050   
4  0.4459  ...  0.0156  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072   

       57      58      59  
0  0.0084  0.0090  0.0032  
1  0.0049  0.0052  0.0044  
2  0.0164  0.0095  0.0078  
3  0.0044  0.0040  0.0117  
4  0.0048  0.0107  0.0094  

[5 rows x 60 columns]

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)
X_train.head()

0       1       2       3       4       5       6       7       8   \
67   0.0368  0.0403  0.0317  0.0293  0.0820  0.1342  0.1161  0.0663  0.0155   
14   0.0124  0.0433  0.0604  0.0449  0.0597  0.0355  0.0531  0.0343  0.1052   
164  0.0163  0.0198  0.0202  0.0386  0.0752  0.1444  0.1487  0.1484  0.2442   
179  0.0394  0.0420  0.0446  0.0551  0.0597  0.1416  0.0956  0.0802  0.1618   
19   0.0126  0.0149  0.0641  0.1732  0.2565  0.2559  0.2947  0.4110  0.4983   

         9   ...      50      51      52      53      54      55      56  \
67   0.0506  ...  0.0058  0.0091  0.0160  0.0160  0.0081  0.0070  0.0135   
14   0.2120  ...  0.0078  0.0083  0.0057  0.0174  0.0188  0.0054  0.0114   
164  0.2822  ...  0.0027  0.0077  0.0026  0.0031  0.0083  0.0020  0.0084   
179  0.2558  ...  0.0118  0.0146  0.0040  0.0114  0.0032  0.0062  0.0101   
19   0.5920  ...  0.0153  0.0092  0.0035  0.0098  0.0121  0.0006  0.0181   

         57      58      59  
67   0.0067  0.0078  0.0068  
14   0.0196  0.0147  0.0062  
164  0.0108  0.0083  0.0033  
179  0.0068  0.0053  0.0087  
19   0.0094  0.0116  0.0063  

[5 rows x 60 columns]

# Using Deep Learning Model
Model without Dropout Layer

In [15]:
import tensorflow as tf
from tensorflow import keras

In [16]:
#number of neurons=number of columns
model = keras.Sequential([
    keras.layers.Dense(60, input_dim=60, activation='relu'),
    keras.layers.Dense(30, activation='relu'),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=100, batch_size=8)

Epoch 1/100
20/20 [==============================] - 0s 889us/step - loss: 0.6867 - accuracy: 0.5256
Epoch 2/100
20/20 [==============================] - 0s 892us/step - loss: 0.6584 - accuracy: 0.5449
Epoch 3/100
20/20 [==============================] - 0s 892us/step - loss: 0.6314 - accuracy: 0.6474
Epoch 4/100
20/20 [==============================] - 0s 1ms/step - loss: 0.5950 - accuracy: 0.7756
Epoch 5/100
20/20 [==============================] - 0s 892us/step - loss: 0.5613 - accuracy: 0.6987
Epoch 6/100
20/20 [==============================] - 0s 840us/step - loss: 0.5238 - accuracy: 0.8205
Epoch 7/100
20/20 [==============================] - 0s 892us/step - loss: 0.4748 - accuracy: 0.7821
Epoch 8/100
20/20 [==============================] - 0s 997us/step - loss: 0.4623 - accuracy: 0.8077
Epoch 9/100
20/20 [==============================] - 0s 892us/step - loss: 0.4573 - accuracy: 0.7628
Epoch 10/100
20/20 [==============================] - 0s 997us/step - loss: 0.4077 - accuracy

20/20 [==============================] - 0s 892us/step - loss: 0.0041 - accuracy: 1.0000
Epoch 83/100
20/20 [==============================] - 0s 945us/step - loss: 0.0041 - accuracy: 1.0000
Epoch 84/100
20/20 [==============================] - 0s 892us/step - loss: 0.0039 - accuracy: 1.0000
Epoch 85/100
20/20 [==============================] - 0s 945us/step - loss: 0.0038 - accuracy: 1.0000
Epoch 86/100
20/20 [==============================] - 0s 840us/step - loss: 0.0037 - accuracy: 1.0000
Epoch 87/100
20/20 [==============================] - 0s 892us/step - loss: 0.0034 - accuracy: 1.0000
Epoch 88/100
20/20 [==============================] - 0s 840us/step - loss: 0.0032 - accuracy: 1.0000
Epoch 89/100
20/20 [==============================] - 0s 885us/step - loss: 0.0032 - accuracy: 1.0000
Epoch 90/100
20/20 [==============================] - 0s 840us/step - loss: 0.0030 - accuracy: 1.0000
Epoch 91/100
20/20 [==============================] - 0s 840us/step - loss: 0.0030 - accuracy: 

In [17]:

model.evaluate(X_test, y_test)

2/2 [==============================] - 0s 1ms/step - loss: 1.4327 - accuracy: 0.7308


[1.4326711893081665, 0.7307692170143127]

In [19]:
y_pred = model.predict(X_test)
print(y_pred[:10])

[[7.9137452e-12]
 [9.7571969e-01]
 [9.9956656e-01]
 [1.1588518e-07]
 [9.9998933e-01]
 [9.9859095e-01]
 [1.3730228e-01]
 [9.9999785e-01]
 [7.2187643e-09]
 [9.9999368e-01]]


In [20]:
y_pred = np.round(y_pred)
print(y_pred[:10])

[[0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]]


In [21]:
y_test[:10]

R
186  0
155  0
165  0
200  0
58   1
34   1
151  0
18   1
202  0
62   1

In [22]:
from sklearn.metrics import confusion_matrix , classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.70      0.85      0.77        27
           1       0.79      0.60      0.68        25

    accuracy                           0.73        52
   macro avg       0.74      0.73      0.72        52
weighted avg       0.74      0.73      0.73        52



In [23]:
modeld = keras.Sequential([
    keras.layers.Dense(60, input_dim=60, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(30, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(1, activation='sigmoid')
])

modeld.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

modeld.fit(X_train, y_train, epochs=100, batch_size=8)

Epoch 1/100
20/20 [==============================] - 0s 1ms/step - loss: 0.7166 - accuracy: 0.5321
Epoch 2/100
20/20 [==============================] - 0s 945us/step - loss: 0.7553 - accuracy: 0.4487
Epoch 3/100
20/20 [==============================] - 0s 1ms/step - loss: 0.7128 - accuracy: 0.4551
Epoch 4/100
20/20 [==============================] - 0s 1ms/step - loss: 0.7042 - accuracy: 0.5385
Epoch 5/100
20/20 [==============================] - 0s 1ms/step - loss: 0.6850 - accuracy: 0.5449
Epoch 6/100
20/20 [==============================] - 0s 1ms/step - loss: 0.6836 - accuracy: 0.5321
Epoch 7/100
20/20 [==============================] - 0s 1ms/step - loss: 0.7054 - accuracy: 0.4679
Epoch 8/100
20/20 [==============================] - 0s 1ms/step - loss: 0.6786 - accuracy: 0.5449
Epoch 9/100
20/20 [==============================] - 0s 1ms/step - loss: 0.6917 - accuracy: 0.5705
Epoch 10/100
20/20 [==============================] - 0s 1ms/step - loss: 0.6835 - accuracy: 0.5769
Epoch 1

20/20 [==============================] - 0s 1ms/step - loss: 0.3114 - accuracy: 0.8846
Epoch 83/100
20/20 [==============================] - 0s 1ms/step - loss: 0.3173 - accuracy: 0.8462
Epoch 84/100
20/20 [==============================] - 0s 1ms/step - loss: 0.2891 - accuracy: 0.8846
Epoch 85/100
20/20 [==============================] - 0s 1ms/step - loss: 0.3074 - accuracy: 0.8590
Epoch 86/100
20/20 [==============================] - 0s 1ms/step - loss: 0.2775 - accuracy: 0.8910
Epoch 87/100
20/20 [==============================] - 0s 1ms/step - loss: 0.3115 - accuracy: 0.8910
Epoch 88/100
20/20 [==============================] - 0s 1ms/step - loss: 0.2848 - accuracy: 0.9038
Epoch 89/100
20/20 [==============================] - 0s 1ms/step - loss: 0.2932 - accuracy: 0.9038
Epoch 90/100
20/20 [==============================] - 0s 997us/step - loss: 0.2459 - accuracy: 0.9103
Epoch 91/100
20/20 [==============================] - 0s 945us/step - loss: 0.3070 - accuracy: 0.8526
Epoch 92/

In [24]:
modeld.evaluate(X_test, y_test)

2/2 [==============================] - 0s 2ms/step - loss: 0.5365 - accuracy: 0.7500


[0.5365385413169861, 0.75]

In [25]:
y_pred = modeld.predict(X_test).reshape(-1)
print(y_pred[:10])

# round the values to nearest integer ie 0 or 1
y_pred = np.round(y_pred)
print(y_pred[:10])

[9.3002462e-05 9.4048572e-01 9.7369134e-01 1.6271710e-02 9.9990433e-01
 7.9819089e-01 7.2572124e-01 9.9995279e-01 8.5092783e-03 9.9995553e-01]
[0. 1. 1. 0. 1. 1. 1. 1. 0. 1.]


In [26]:
from sklearn.metrics import confusion_matrix , classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.75      0.78      0.76        27
           1       0.75      0.72      0.73        25

    accuracy                           0.75        52
   macro avg       0.75      0.75      0.75        52
weighted avg       0.75      0.75      0.75        52

